version: '3.0'

services:
  auth:
    container_name: auth
    build: 
      context: .
      dockerfile: auth/Dockerfile
    ports:
      - "8081:8081"
    volumes:
      - ./auth:/opt/corda/auth

  zone:
    container_name: zone
    build: 
      context: .
      dockerfile: zone/Dockerfile
    ports:
      - "5061:5061"
      - "5063:5063"
    volumes:
      - ./auth:/opt/corda/auth

  farm:
    container_name: farm
    build: 
      context: .
      dockerfile: farm/Dockerfile
    ports:
      - "8080:8080"
    volumes:
      - ./farm:/opt/corda/farm 

  angel:
    container_name: angel
    build: 
      context: .
      dockerfile: angel/Dockerfile
    volumes:
      - ./angel:/opt/corda/angel 

  identity-manager:
    container_name: identity-manager
    build: 
      context: .
      dockerfile: identity-manager/Dockerfile
    ports:
      - "10022:10022"
      - "10000:10000"
      - "5051:5051"
    volumes:
      - ./identity-manager:/opt/corda/identity-manager

  notary: 
    container_name: notary
    build:
      context: .
      dockerfile: notary/Dockerfile
    ports:
      - "12001:12001"
      - "60101:60101"
      - "60102:60102"
      - "60103:60103"
      - "60100:60100"
    volumes: 
    - ./notary:/opt/corda/notary
    - ./identity-manager/trust-stores:/opt/corda/notary/trust-stores
    depends_on: 
    - identity-manager

  network-map:
    container_name: network-map
    build:
      context: .
      dockerfile: network-map/Dockerfile
    ports:
      - "20000:20000"
    volumes:
      - ./network-map:/opt/corda/network-map
      - ./identity-manager/trust-stores:/opt/corda/network-map/trust-stores
      - ./identity-manager/key-stores:/opt/corda/network-map/key-stores
      - ./notary/additional-node-infos:/opt/corda/network-map/notary-info
    depends_on: 
      - identity-manager
      - notary
  
  node01: 
    build:
      context: .
      dockerfile: node01/Dockerfile
    ports:
      - "61100:61100"
      - "61101:61101"
    volumes:
      - ./node01:/opt/corda/node01
      - ./identity-manager/trust-stores:/opt/corda/node01/trust-stores
      - ./identity-manager/key-stores:/opt/corda/node01/key-stores
    depends_on: 
      - identity-manager
      - network-map