version: '3.0'

services:
  notary: 
    container_name: notary
    build:
      context: .
      dockerfile: notary/Dockerfile
    ports:
      - "12001:12001"
      - "60101:60101"
      - "60102:60102"
      - "60103:60103"
      - "60100:60100"
    command: java -jar libs/corda.jar
    volumes: 
    - ./notary:/opt/corda/notary

  node01: 
    build:
      context: .
      dockerfile: node01/Dockerfile
    ports:
      - "61100:61100"
      - "61101:61101"
    volumes:
      - ./node01:/opt/corda/node01
      - ./identity-manager/trust-stores:/opt/corda/node01/trust-stores
      - ./identity-manager/key-stores:/opt/corda/node01/key-stores
    command: java -jar libs/corda.jar